### ISSUE TITLE
Arduino IDE doesn't start

### ISSUE THREAD

**Issue by Nitheshnithu121** [Nitheshnithu121/Cloud-and-IoT-based-Health-Monitoring-System#1]
I have a problem when i start Arduino IDE it starts, then initializes packages and just vanishes......
The output on running debugger is as follows:
C:\Program Files (x86)\Arduino>arduino_debug.exe
Set log4j store directory C:\Users\user\AppData\Local\Arduino15
Loading configuration...
Initializing packages...
java.lang.NullPointerException
at cc.arduino.contributions.packages.ContributionsIndexer.parseIndex(ContributionsIndexer.java:134)
at processing.app.BaseNoGui.initPackages(BaseNoGui.java:483)
at processing.app.Base.(Base.java:273)
at processing.app.Base.main(Base.java:150)

Cloud any one please help me solve this problem

**Comment by Nitheshnithu121** [comment]
Windows:

remove file C:\Users\YourUsername\AppData\Local\Arduino15\package_index.json
remove folder C:\Users\YourUsername\AppData\Local\Arduino15\cache
